DROP TABLE sessions;
DROP TABLE verification_codes;
DROP TABLE board_card_checklist_items;
DROP TABLE board_card_checklists;
DROP TABLE board_card_stats;
DROP TABLE board_cards;
DROP TABLE board_columns;
DROP TABLE boards;
DROP TABLE users;
